# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 154dd70b32f4cc8ebdb16705c1dab7985a171e43e0cddc1ea2f31161f20ae6775113bfd79245b125a04055de46bacbd006f5c100042ee2bb6f11fb0109cc3785

test:
  secret_key_base: 47afd229625ec2881643ef355ee8d5b7055396f0e4315c9fd1bd985ab12a2612994ded896058ea45981d5edb1ca7830b38d73c7fe9423799631411d842c13303

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
